const INITIAL_STATE = 'INITIAL_STATE';
const ADD_FRIEND = 'ADD_FRIEND';
const REMOVE_FRIEND = 'REMOVE_FRIEND';
const UPDATE_FRIEND = 'UPDATE_FRIEND';

export { INITIAL_STATE, ADD_FRIEND, REMOVE_FRIEND, UPDATE_FRIEND };